name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger only when main is pushed

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1

    - name: Check Salesforce CLI Version
      run: sfdx --version

    - name: Write private key to file
      run: echo "${{ secrets.PROD_SERVERKEY }}" > server.key

    - name: Authenticate to Production Org using JWT
      run: |
        sfdx auth:jwt:grant \
          --client-id ${{ secrets.PROD_CLIENTID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.PROD_USERNAME }} \
          --instance-url https://login.salesforce.com \
          --alias moodleprod

    - name: Deploy to Production Org
      run: |
        sfdx project deploy start \
          --target-org moodleprod \
          --wait 10 \
          --verbose
