name: Deploy to Development

on:
  push:
    branches:
      - main  # Trigger only when main is pushed

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1

    - name: Write private key to file
      run: echo "${{ secrets.DEV_SERVERKEY }}" > server.key

    - name: Authenticate to Production Org using JWT
      run: |
        sfdx auth:jwt:grant \
          --client-id ${{ secrets.DEV_CLIENTID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.DEV_USERNAME }} \
          --instance-url https://login.salesforce.com \
          --alias moodledev

    - name: Deploy to Devlopment Org
      run: |
        sf project deploy start --manifest manifest/package.xml --target-org moodledev --wait 10
