name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger only when main is pushed

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      uses: sfdx-actions/setup-sfdx@v1

    - name: Write private key to file
      run: echo "${{ secrets.PROD_SERVERKEY }}" > server.key

    - name: Authenticate to Production Org using JWT
      run: |
        sfdx auth:jwt:grant \
          --clientid ${{ secrets.PROD_CLIENTID }} \
          --jwtkeyfile server.key \
          --username ${{ secrets.PROD_USERNAME }} \
          --instanceurl https://login.salesforce.com \
          --setalias moodleprod

    - name: Deploy to Production Org
      run: |
        sfdx force:source:deploy \
          --targetusername prod \
          --sourcepath force-app \
          --checkonly false \
          --testlevel RunLocalTests \
          --wait 10
