name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment to deploy
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Set deployment environment
        id: set-env
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "CLIENT_ID=${{ secrets.DEV_CLIENTID }}" >> $GITHUB_ENV
            echo "SERVER_KEY=${{ secrets.DEV_SERVERKEY }}" >> $GITHUB_ENV
            echo "USERNAME=${{ secrets.DEV_USERNAME }}" >> $GITHUB_ENV
            echo "ALIAS=moodledev" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "qa" ]]; then
            echo "CLIENT_ID=${{ secrets.QA_CLIENTID }}" >> $GITHUB_ENV
            echo "SERVER_KEY=${{ secrets.QA_SERVERKEY }}" >> $GITHUB_ENV
            echo "USERNAME=${{ secrets.QA_USERNAME }}" >> $GITHUB_ENV
            echo "ALIAS=moodleqa" >> $GITHUB_ENV
          else
            echo "CLIENT_ID=${{ secrets.PROD_CLIENTID }}" >> $GITHUB_ENV
            echo "SERVER_KEY=${{ secrets.PROD_SERVERKEY }}" >> $GITHUB_ENV
            echo "USERNAME=${{ secrets.PROD_USERNAME }}" >> $GITHUB_ENV
            echo "ALIAS=moodleprod" >> $GITHUB_ENV
          fi

      - name: Write server key
        run: echo "${SERVER_KEY}" > server.key

      - name: Authenticate to selected org
        run: |
          sfdx auth:jwt:grant \
            --client-id $CLIENT_ID \
            --jwt-key-file server.key \
            --username $USERNAME \
            --instance-url https://login.salesforce.com \
            --alias $ALIAS

      - name: Deploy to selected org
        run: |
          sf project deploy start -p force-app -u $ALIAS --wait 10

